"""The shared behavioural corpus for the Rust/Python parity fixtures.

Each case is `(name, argv, stdin)`. `tools/capture_oracle.py` runs the corpus
against the original Rust binary and records stdout/stderr/exit status into
`tests/oracle.json`; `tests/test_parity.py` replays the same corpus against this
port and asserts the recordings match byte for byte.

Keeping the corpus in one place means a case added here is automatically both
recorded and checked.
"""

CASES = [
    # -- the three cases migrated from tests/cli.rs ------------------------
    (
        "find_by_class",
        [".hi"],
        '<html><head></head><body><div class="hi"><a href="/foo/bar">Hello</a></div></body></html>',
    ),
    (
        "find_by_id",
        ["#my-id"],
        '<html><head></head><body><div id="my-id"><a href="/foo/bar">Hello</a></div></body></html>',
    ),
    (
        "remove_links",
        ["#my-id", "--remove-nodes", "a"],
        '<html><head></head><body><div id="my-id"><a href="/foo/bar">Hello</a></div></body></html>',
    ),
    # -- defaults and the whole-document path -----------------------------
    ("default_selector", [], "<p>hello</p>"),
    ("explicit_html", ["html"], "<p>hello</p>"),
    ("doctype_is_not_selected", [], "<!DOCTYPE html><p>hi</p>"),
    ("no_match_prints_nothing", [".nope"], "<p>hi</p>"),
    ("empty_input", [], ""),
    (
        "multiple_matches_each_on_own_line",
        ["li"],
        "<ul><li>one</li><li>two</li><li>three</li></ul>",
    ),
    # -- serializer edge cases --------------------------------------------
    ("void_element_roundtrip", ["head"], '<head><link  href="/s.css" rel="stylesheet"/></head>'),
    ("attribute_order_is_source_order", ["a"], '<a z="1" m="2" a="3" href="/x">t</a>'),
    ("attribute_escaping", ["a"], '<a title=\'q"&amp;&lt;&gt;\'>t</a>'),
    ("text_escaping", ["p"], "<p>a &amp; b &lt; c &gt; d</p>"),
    ("nbsp_is_named_entity", ["p"], "<p>a\u00a0b</p>"),
    ("script_text_is_raw", ["script"], "<script>if (a < b && c) {}</script>"),
    ("style_text_is_raw", ["style"], "<style>a > b { color: red }</style>"),
    ("comment_is_preserved", ["body"], "<body><!-- hi <b> --></body>"),
    ("empty_attribute_value", ["input"], "<input disabled>"),
    ("svg_namespace_attributes", ["svg"], '<svg xmlns:xlink="http://www.w3.org/1999/xlink"><a xlink:href="/z">x</a></svg>'),
    ("template_contents_are_split_off", ["body"], "<body><template><p>inside</p></template></body>"),
    ("adjacent_text_is_merged", ["p"], "<p>a&amp;b&lt;c</p>"),
    # -- selectors ---------------------------------------------------------
    ("selector_list", ["h1, h2"], "<h1>a</h1><h2>b</h2><h3>c</h3>"),
    ("child_combinator", ["div > p"], "<div><p>yes</p><section><p>no</p></section></div>"),
    ("descendant_combinator", ["div p"], "<div><p>yes</p><section><p>also</p></section></div>"),
    ("next_sibling_combinator", ["h1 + p"], "<h1>t</h1><p>yes</p><p>no</p>"),
    ("later_sibling_combinator", ["h1 ~ p"], "<h1>t</h1><p>yes</p><span>x</span><p>also</p>"),
    ("attribute_exists", ["[data-x]"], '<a data-x>1</a><a>2</a>'),
    ("attribute_equals", ['[rel="next"]'], '<a rel="next">1</a><a rel="prev">2</a>'),
    ("attribute_includes", ['[class~="b"]'], '<p class="a b c">1</p><p class="ab">2</p>'),
    ("attribute_dash_match", ['[lang|="en"]'], '<p lang="en-GB">1</p><p lang="fr">2</p><p lang="en">3</p>'),
    ("attribute_prefix", ['[href^="/a"]'], '<a href="/ab">1</a><a href="/b">2</a>'),
    ("attribute_suffix", ['[href$=".pdf"]'], '<a href="x.pdf">1</a><a href="x.txt">2</a>'),
    ("attribute_substring", ['[href*="mid"]'], '<a href="a-mid-b">1</a><a href="ab">2</a>'),
    ("attribute_case_insensitive_flag", ['[rel="NEXT" i]'], '<a rel="next">1</a><a rel="other">2</a>'),
    ("attribute_case_sensitive_default", ['[rel="NEXT"]'], '<a rel="next">1</a><a rel="NEXT">2</a>'),
    ("attribute_flag_s_no_match", ['[rel="NEXT" s]'], '<a rel="next">1</a>'),
    ("attribute_flag_s_match", ['[rel="next" s]'], '<a rel="next">1</a>'),
    ("class_is_case_sensitive", [".Hi"], '<p class="hi">1</p><p class="Hi">2</p>'),
    ("id_is_case_sensitive", ["#Hi"], '<p id="hi">1</p><p id="Hi">2</p>'),
    ("universal_selector", ["*"], "<p>a</p>"),
    ("type_selector_is_case_insensitive", ["P"], "<p>a</p>"),
    ("first_child", ["li:first-child"], "<ul><li>1</li><li>2</li></ul>"),
    ("last_child", ["li:last-child"], "<ul><li>1</li><li>2</li></ul>"),
    ("only_child", ["li:only-child"], "<ul><li>1</li></ul><ol><li>2</li><li>3</li></ol>"),
    ("nth_child", ["li:nth-child(2n)"], "<ul><li>1</li><li>2</li><li>3</li><li>4</li></ul>"),
    ("nth_child_odd", ["li:nth-child(odd)"], "<ul><li>1</li><li>2</li><li>3</li></ul>"),
    ("nth_child_formula", ["li:nth-child(2n+1)"], "<ul><li>1</li><li>2</li><li>3</li></ul>"),
    ("nth_last_child", ["li:nth-last-child(1)"], "<ul><li>1</li><li>2</li></ul>"),
    ("first_of_type", ["p:first-of-type"], "<div><span>s</span><p>1</p><p>2</p></div>"),
    ("last_of_type", ["p:last-of-type"], "<div><p>1</p><p>2</p><span>s</span></div>"),
    ("only_of_type", ["p:only-of-type"], "<div><span>s</span><p>1</p></div>"),
    ("nth_of_type", ["p:nth-of-type(2)"], "<div><p>1</p><span>s</span><p>2</p></div>"),
    ("root_pseudo", [":root"], "<p>a</p>"),
    ("scope_pseudo", [":scope"], "<p>a</p>"),
    ("empty_pseudo", ["p:empty"], "<p></p><p>x</p>"),
    ("not_pseudo", ["p:not(.skip)"], '<p>1</p><p class="skip">2</p>'),
    ("link_pseudo", [":link"], '<a href="/x">1</a><a>2</a>'),
    ("any_link_pseudo", [":any-link"], '<a href="/x">1</a><a>2</a>'),
    ("checked_never_matches", ["input:checked"], "<input checked><input>"),
    ("disabled_never_matches", ["input:disabled"], "<input disabled><input>"),
    ("hover_never_matches", ["a:hover"], '<a href="/x">1</a>'),
    # -- selector parse failures (all panic with exit 101) -----------------
    ("bad_selector_unbalanced", ["(("], "<p>x</p>"),
    ("bad_selector_pseudo_element", ["p::before"], "<p>x</p>"),
    ("bad_selector_unknown_pseudo", ["p:nonsense"], "<p>x</p>"),
    ("bad_selector_empty_string", [""], "<p>x</p>"),
    ("bad_selector_dangling_combinator", ["p >"], "<p>x</p>"),
    ("bad_selector_nested_not", ["p:not(:not(a))"], "<p>x</p>"),
    ("bad_selector_namespace_prefix", ["svg|a"], "<p>x</p>"),
    ("bad_selector_is_unsupported", ["p:is(.a)"], "<p>x</p>"),
    ("bad_selector_has_unsupported", ["p:has(a)"], "<p>x</p>"),
    ("bad_attribute_flag_unknown", ['[rel="a" x]'], "<p>x</p>"),
    # -- --remove-nodes ----------------------------------------------------
    (
        "remove_nodes_only_removes_first_match",
        ["div", "-r", "a"],
        '<div><a href="/1">1</a><a href="/2">2</a></div>',
    ),
    (
        "remove_nodes_multiple_selectors",
        ["div", "-r", "a", "-r", "span"],
        "<div><span>s</span><a>a</a><b>b</b></div>",
    ),
    (
        "remove_nodes_invalid_selector_is_ignored",
        ["div", "-r", "(("],
        "<div><a>a</a></div>",
    ),
    (
        "remove_nodes_can_remove_self_match",
        ["div", "-r", "div"],
        "<div><p>inner</p></div>",
    ),
    (
        "remove_nodes_affects_later_iteration",
        ["p", "-r", "p"],
        "<div><p>1</p><p>2</p><p>3</p></div>",
    ),
    # -- --attributes ------------------------------------------------------
    ("attributes_single", ["a", "-a", "href"], '<a href="/1">1</a><a href="/2">2</a>'),
    ("attributes_multiple", ["a", "-a", "href", "-a", "rel"], '<a href="/1" rel="next">1</a>'),
    ("attributes_missing_prints_nothing", ["a", "-a", "nope"], '<a href="/1">1</a>'),
    ("attributes_beat_text", ["a", "-a", "href", "-t"], '<a href="/1">1</a>'),
    ("attributes_beat_pretty", ["a", "-a", "href", "-p"], '<a href="/1">1</a>'),
    # -- --text ------------------------------------------------------------
    ("text_simple", ["p", "-t"], "<p>hello <b>world</b></p>"),
    ("text_includes_whitespace", ["div", "-t"], "<div>\n  <p>a</p>\n  <p>b</p>\n</div>"),
    (
        "text_ignore_whitespace",
        ["div", "-t", "-i"],
        "<div>\n  <p>a</p>\n  <p>b</p>\n</div>",
    ),
    ("text_of_empty_node", ["p", "-t"], "<p></p>"),
    ("text_beats_pretty", ["p", "-t", "-p"], "<p>hi</p>"),
    ("text_entities_are_decoded", ["p", "-t"], "<p>a &amp; b</p>"),
    # -- --pretty ----------------------------------------------------------
    ("pretty_simple", ["body", "-p"], "<body><div><p>hi</p></div></body>"),
    ("pretty_inline_elements", ["p", "-p"], "<p>Hello <b>bold</b> and <i>italic</i> text</p>"),
    ("pretty_void_element", ["head", "-p"], '<head><link href="/s.css" rel="stylesheet"></head>'),
    ("pretty_nested", ["body", "-p"], "<body><ul><li>1</li><li>2</li></ul></body>"),
    ("pretty_whitespace_only_text_dropped", ["div", "-p"], "<div>\n   <p>x</p>\n</div>"),
    # -- --base / --detect-base -------------------------------------------
    ("base_rewrites_relative", ["a", "-b", "https://mgdm.net"], '<a href="/foo/bar">1</a>'),
    ("base_leaves_absolute", ["a", "-b", "https://mgdm.net"], '<a href="https://example.org/x">1</a>'),
    ("base_relative_no_slash", ["a", "-b", "https://mgdm.net/dir/page"], '<a href="left.html">1</a>'),
    ("base_four_slashes", ["a", "-b", "https://mgdm.net"], '<a href="////evil.com/x">1</a>'),
    ("base_protocol_relative", ["a", "-b", "https://mgdm.net"], '<a href="//other.org/x">1</a>'),
    ("base_empty_href", ["a", "-b", "https://mgdm.net"], '<a href="">1</a>'),
    ("base_only_applies_to_matched_node", ["div", "-b", "https://mgdm.net"], '<div><a href="/x">1</a></div>'),
    ("base_applies_to_link", ["link", "-b", "https://mgdm.net"], '<link href="/s.css">'),
    ("base_applies_to_area", ["area", "-b", "https://mgdm.net"], '<map name="p"><area coords="1" href="l.html" shape="circle"></map>'),
    ("base_invalid_is_ignored", ["a", "-b", "not a url"], '<a href="/x">1</a>'),
    ("base_default_port_elided", ["a", "-b", "https://mgdm.net:443"], '<a href="/x">1</a>'),
    ("base_dot_segments", ["a", "-b", "https://mgdm.net/a/b/c"], '<a href="../d">1</a>'),
    (
        "detect_base_from_document",
        ["a", "-B"],
        '<html><head><base href="https://example.org/"></head><body><a href="/x">1</a></body></html>',
    ),
    (
        "detect_base_missing_falls_back_to_nothing",
        ["a", "-B"],
        '<html><head></head><body><a href="/x">1</a></body></html>',
    ),
    (
        "detect_base_beats_explicit_base",
        ["a", "-B", "-b", "https://mgdm.net"],
        '<html><head><base href="https://example.org/"></head><body><a href="/x">1</a></body></html>',
    ),
    (
        "detect_base_falls_back_to_explicit_base",
        ["a", "-B", "-b", "https://mgdm.net"],
        '<html><head></head><body><a href="/x">1</a></body></html>',
    ),
    (
        "detect_base_invalid_href",
        ["a", "-B"],
        '<html><head><base href="nonsense"></head><body><a href="/x">1</a></body></html>',
    ),
    (
        "detect_base_without_href",
        ["a", "-B"],
        '<html><head><base target="_blank"></head><body><a href="/x">1</a></body></html>',
    ),
    # -- CLI surface -------------------------------------------------------
    ("help_long", ["--help"], ""),
    ("help_short", ["-h"], ""),
    ("version_long", ["--version"], ""),
    ("version_short", ["-V"], ""),
    ("unknown_flag", ["--nope"], ""),
    ("filename_dash_is_stdin", ["-f", "-", "p"], "<p>hi</p>"),
    ("missing_input_file", ["-f", "/nonexistent/file.html", "p"], ""),
    ("unwritable_output_file", ["-o", "/nonexistent/dir/out.html", "p"], "<p>x</p>"),
    ("missing_value_for_filename", ["-f"], ""),
    ("missing_value_for_base", ["--base"], ""),
    ("unknown_short_flag", ["-x"], ""),
    ("too_many_positionals", ["p", "q"], "<p>x</p>"),
    ("double_dash_then_positional", ["--", "p"], "<p>hi</p>"),
    ("combined_short_flags", ["-tp", "p"], "<p>hi</p>"),
    ("long_equals_syntax", ["--filename=-", "p"], "<p>hi</p>"),
    ("short_attached_value", ["-f-", "p"], "<p>hi</p>"),
    ("repeated_flag_is_fine", ["-t", "-t", "p"], "<p>hi</p>"),
    ("selector_after_options", ["-t", "p"], "<p>hi</p>"),
    ("repeated_value_option_filename", ["-f", "-", "-f", "-", "p"], "<p>hi</p>"),
    ("repeated_value_option_base", ["-b", "https://a.example", "-b", "https://b.example", "a"],
     '<a href="/x">1</a>'),
    ("repeated_long_flag", ["--text", "--text", "p"], "<p>hi</p>"),
    # -- selector forms the first parity run turned up -------------------
    ("universal_with_class", ["*.hi"], '<p class="hi">a</p><p>b</p>'),
    ("explicit_no_namespace_type", ["|p"], "<p>a</p>"),
    ("any_namespace_type", ["*|a"], '<svg><a>s</a></svg><a href="/x">h</a>'),
    ("attr_any_namespace", ['[*|href]'],
     '<svg xmlns:xlink="http://www.w3.org/1999/xlink"><a xlink:href="/z">x</a></svg>'),
    ("attr_case_insensitive_html_list_type", ['[type="TEXT"]'], '<input type="text">'),
    ("attr_case_insensitive_html_list_lang", ['[lang="EN"]'], '<p lang="en">a</p>'),
    ("attr_case_sensitive_class_attr", ['[class="HI"]'], '<p class="hi">a</p>'),
    ("attr_case_sensitive_href", ['[href="/X"]'], '<a href="/x">a</a>'),
    ("attr_case_insensitive_on_svg_element", ['[type="TEXT"]'],
     '<svg><rect type="text"></rect></svg>'),
    ("nth_child_negative_step", ["li:nth-child(-n+2)"],
     "<ul><li>1</li><li>2</li><li>3</li></ul>"),
    ("escaped_class_selector", [".a\\.b"], '<p class="a.b">x</p><p class="a">y</p>'),
    ("single_quoted_attr_value", ["[rel='next']"], '<a rel="next">1</a>'),
    ("unquoted_attr_value", ["[rel=next]"], '<a rel="next">1</a>'),
    ("selector_leading_trailing_space", ["  p  "], "<p>a</p>"),
    # -- reference-lifetime cases the differential sweep turned up ---------
    # Detaching frees the node, so the traversal ends where kuchikiki's `Rc`s
    # run out rather than where the tree structure would suggest. See the
    # reference-lifetime note in htmlq/vendor/kuchikiki.py.
    ("detach_truncates_after_first_child",
     ["p, i, u, s, b", "-r", "p"],
     "<div><p><i>I</i><u>U</u><s>S</s></p><b>B</b></div>"),
    ("detach_truncates_after_nested_first_child",
     ["p, i, x, u, b", "-r", "p"],
     "<div><p><i><x>X</x></i><u>U</u></p><b>B</b></div>"),
    ("detach_with_text_only_child_ends_walk",
     ["p, b", "-r", "p"],
     "<div><p>T</p><b>B</b></div>"),
    ("detach_after_earlier_sibling_matched",
     ["b, p, i", "-r", "p"],
     "<div><b>B</b><p><i>I</i></p></div>"),
    ("detach_of_inner_node_frees_its_tail",
     ["p, i, s, em, u, b", "-r", "i"],
     "<div><p><i><s>S</s><em>E</em></i><u>U</u></p><b>F</b></div>"),
    ("remove_universal_frees_rejected_candidates",
     ["div, span, i", "-r", "*"],
     "<div><p>one<p>two<span>three</div>"),
    ("remove_universal_on_html",
     ["div, p", "-r", "html"],
     "<div><p>one</p><p>two</p></div>"),
]
